import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'active_hole_screen.dart';

// ─── Entry point ──────────────────────────────────────────────────────────────
class StartNightScreen extends StatefulWidget {
  const StartNightScreen({super.key});

  @override
  State<StartNightScreen> createState() => _StartNightScreenState();
}

class _StartNightScreenState extends State<StartNightScreen> {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  // Shared state across steps
  String nightName = '';
  double numBars = 6;
  String vibe = 'Competitive';
  String difficulty = 'Normal';
  bool challengesOn = true;
  bool autoGenerated = true;
  String scoringMode = 'Chaos';

  void _next() {
    if (_currentPage < 3) {
      _pageController.nextPage(
        duration: const Duration(milliseconds: 350),
        curve: Curves.easeInOut,
      );
    }
  }

  void _back() {
    if (_currentPage == 0) {
      Navigator.pop(context);
    } else {
      _pageController.previousPage(
        duration: const Duration(milliseconds: 350),
        curve: Curves.easeInOut,
      );
    }
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF060608),
      body: Stack(
        children: [
          // Background — same style as home
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Color(0xFF0B1A14), Color(0xFF060608)],
              ),
            ),
          ),
          const _NightBokeh(),
          Container(
            decoration: const BoxDecoration(
              gradient: RadialGradient(
                center: Alignment(0.0, 0.5),
                radius: 0.7,
                colors: [Color(0x1E7B2CBF), Colors.transparent],
              ),
            ),
          ),

          // Pages
          SafeArea(
            child: Column(
              children: [
                Expanded(
                  child: PageView(
                    controller: _pageController,
                    physics: const NeverScrollableScrollPhysics(),
                    onPageChanged: (i) => setState(() => _currentPage = i),
                    children: [
                      _Step1(
                        nightName: nightName,
                        numBars: numBars,
                        vibe: vibe,
                        onNameChanged: (v) => setState(() => nightName = v),
                        onBarsChanged: (v) => setState(() => numBars = v),
                        onVibeChanged: (v) => setState(() => vibe = v),
                        onBack: _back,
                        onNext: _next,
                      ),
                      _Step2(onBack: _back, onNext: _next),
                      _Step3(onBack: _back, onNext: _next),
                      _Step4(
                        difficulty: difficulty,
                        challengesOn: challengesOn,
                        autoGenerated: autoGenerated,
                        scoringMode: scoringMode,
                        onDifficultyChanged: (v) => setState(() => difficulty = v),
                        onChallengesChanged: (v) => setState(() => challengesOn = v),
                        onAutoGenChanged: (v) => setState(() => autoGenerated = v),
                        onScoringChanged: (v) => setState(() => scoringMode = v),
                        onBack: _back,
                        onStart: () => Navigator.pushReplacement(
                          context,
                          MaterialPageRoute(builder: (_) => const ActiveHoleScreen()),
                        ),
                      ),
                    ],
                  ),
                ),

                // Page dots
                Padding(
                  padding: const EdgeInsets.only(bottom: 20),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: List.generate(4, (i) {
                      final active = i == _currentPage;
                      return AnimatedContainer(
                        duration: const Duration(milliseconds: 250),
                        margin: const EdgeInsets.symmetric(horizontal: 4),
                        width: active ? 18 : 6,
                        height: 6,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(3),
                          color: active
                              ? const Color(0xFF7CB342)
                              : const Color(0xFF333333),
                        ),
                      );
                    }),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Shared widgets ───────────────────────────────────────────────────────────

class _StepHeader extends StatelessWidget {
  const _StepHeader({required this.title, required this.subtitle, required this.onBack});
  final String title, subtitle;
  final VoidCallback onBack;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(8, 12, 16, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              IconButton(
                icon: const Icon(Icons.arrow_back_ios, color: Colors.white, size: 20),
                onPressed: onBack,
              ),
              Text(
                title,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 24,
                  fontWeight: FontWeight.w800,
                ),
              ),
            ],
          ),
          Padding(
            padding: const EdgeInsets.only(left: 16),
            child: Text(
              subtitle,
              style: const TextStyle(color: Color(0xFF888888), fontSize: 13),
            ),
          ),
          const SizedBox(height: 8),
        ],
      ),
    );
  }
}

class _GreenButton extends StatelessWidget {
  const _GreenButton({required this.label, required this.onTap});
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.symmetric(vertical: 17),
        decoration: BoxDecoration(
          color: const Color(0xFF1A2A0A),
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: const Color(0xFF7CB342), width: 1.5),
          boxShadow: const [
            BoxShadow(color: Color(0x667CB342), blurRadius: 18, spreadRadius: 2),
            BoxShadow(color: Color(0x337CB342), blurRadius: 36, spreadRadius: 4),
          ],
        ),
        child: Text(
          label,
          textAlign: TextAlign.center,
          style: const TextStyle(
            color: Colors.white,
            fontSize: 18,
            fontWeight: FontWeight.bold,
          ),
        ),
      ),
    );
  }
}

class _DarkField extends StatelessWidget {
  const _DarkField({required this.hint, required this.onChanged, this.initialValue = ''});
  final String hint, initialValue;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      initialValue: initialValue,
      onChanged: onChanged,
      style: const TextStyle(color: Colors.white, fontSize: 16),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: const TextStyle(color: Color(0xFF555555)),
        filled: true,
        fillColor: const Color(0xFF111118),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Color(0xFF2A2A3A), width: 1),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Color(0xFF7B2CBF), width: 1.5),
        ),
      ),
    );
  }
}

// ─── Step 1: Create Your Night ────────────────────────────────────────────────
class _Step1 extends StatelessWidget {
  const _Step1({
    required this.nightName, required this.numBars, required this.vibe,
    required this.onNameChanged, required this.onBarsChanged, required this.onVibeChanged,
    required this.onBack, required this.onNext,
  });

  final String nightName, vibe;
  final double numBars;
  final ValueChanged<String> onNameChanged, onVibeChanged;
  final ValueChanged<double> onBarsChanged;
  final VoidCallback onBack, onNext;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _StepHeader(
            title: 'Create Your Night',
            subtitle: 'Night Name · Optional',
            onBack: onBack,
          ),
          const SizedBox(height: 16),

          // Night Name
          const Text('Night Name', style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
          const SizedBox(height: 8),
          _DarkField(
            hint: "John's Birthday Run",
            initialValue: nightName,
            onChanged: onNameChanged,
          ),
          const SizedBox(height: 6),
          const Text('Name your pub crawl', style: TextStyle(color: Color(0xFF555555), fontSize: 12)),

          const SizedBox(height: 28),

          // Number of Bars
          const Text('Number of Bars', style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
          const SizedBox(height: 12),
          _BarsSlider(value: numBars, onChanged: onBarsChanged),

          const SizedBox(height: 28),

          // Vibe
          const Text('Vibe', style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          _VibePicker(selected: vibe, onChanged: onVibeChanged),

          const Spacer(),

          _GreenButton(label: 'Continue', onTap: onNext),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

class _BarsSlider extends StatelessWidget {
  const _BarsSlider({required this.value, required this.onChanged});
  final double value;
  final ValueChanged<double> onChanged;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SliderTheme(
          data: SliderTheme.of(context).copyWith(
            trackHeight: 4,
            activeTrackColor: const Color(0xFF7CB342),
            inactiveTrackColor: const Color(0xFF2A2A3A),
            thumbColor: Colors.white,
            thumbShape: _BubbleThumbShape(value.round()),
            overlayColor: const Color(0x227CB342),
          ),
          child: Slider(
            value: value,
            min: 3,
            max: 9,
            divisions: 6,
            onChanged: onChanged,
          ),
        ),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 4),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: const [
              Text('3', style: TextStyle(color: Color(0xFF555555), fontSize: 12)),
              Text('9', style: TextStyle(color: Color(0xFF555555), fontSize: 12)),
            ],
          ),
        ),
      ],
    );
  }
}

class _BubbleThumbShape extends SliderComponentShape {
  final int value;
  const _BubbleThumbShape(this.value);

  @override
  Size getPreferredSize(bool isEnabled, bool isDiscrete) => const Size(28, 28);

  @override
  void paint(PaintingContext context, Offset center, {required Animation<double> activationAnimation,
    required Animation<double> enableAnimation, required bool isDiscrete,
    required TextPainter labelPainter, required RenderBox parentBox,
    required SliderThemeData sliderTheme, required TextDirection textDirection,
    required double value, required double textScaleFactor, required Size sizeWithOverflow}) {
    final canvas = context.canvas;
    canvas.drawCircle(center, 14, Paint()..color = const Color(0xFF7CB342));
    canvas.drawCircle(center, 14, Paint()..color = Colors.white..style = PaintingStyle.stroke..strokeWidth = 2);
    final tp = TextPainter(
      text: TextSpan(text: this.value.toString(),
          style: const TextStyle(color: Colors.white, fontSize: 11, fontWeight: FontWeight.bold)),
      textDirection: TextDirection.ltr,
    )..layout();
    tp.paint(canvas, center - Offset(tp.width / 2, tp.height / 2));
  }
}

class _VibePicker extends StatelessWidget {
  const _VibePicker({required this.selected, required this.onChanged});
  final String selected;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    final options = ['Chill', 'Competitive', '😊'];
    return Row(
      children: options.map((o) {
        final isSelected = o == selected;
        return Padding(
          padding: const EdgeInsets.only(right: 10),
          child: GestureDetector(
            onTap: () => onChanged(o),
            child: AnimatedContainer(
              duration: const Duration(milliseconds: 200),
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
              decoration: BoxDecoration(
                color: isSelected ? const Color(0xFF7B2CBF) : const Color(0xFF111118),
                borderRadius: BorderRadius.circular(22),
                border: Border.all(
                  color: isSelected ? const Color(0xFF9D4EDD) : const Color(0xFF2A2A3A),
                  width: 1.5,
                ),
                boxShadow: isSelected ? const [
                  BoxShadow(color: Color(0x559D4EDD), blurRadius: 12, spreadRadius: 1),
                ] : null,
              ),
              child: Text(
                o,
                style: TextStyle(
                  color: isSelected ? Colors.white : const Color(0xFF777777),
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                  fontSize: 14,
                ),
              ),
            ),
          ),
        );
      }).toList(),
    );
  }
}

// ─── Step 2: Pick Your Area ───────────────────────────────────────────────────
class _Step2 extends StatelessWidget {
  const _Step2({required this.onBack, required this.onNext});
  final VoidCallback onBack, onNext;

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: _StepHeader(
            title: 'Pick Your Area',
            subtitle: 'Select where you want to crawl',
            onBack: onBack,
          ),
        ),

        // Map
        Expanded(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Stack(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(16),
                  child: CustomPaint(
                    painter: _NightMapPainter(),
                    child: Container(),
                  ),
                ),
                // "Best route" chip
                Positioned(
                  bottom: 14,
                  left: 0,
                  right: 0,
                  child: Center(
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                      decoration: BoxDecoration(
                        color: const Color(0xCC111118),
                        borderRadius: BorderRadius.circular(22),
                        border: Border.all(color: const Color(0xFF2A2A3A)),
                      ),
                      child: const Text(
                        'Best route generated for you ✦',
                        style: TextStyle(color: Colors.white, fontSize: 13),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),

        const SizedBox(height: 16),

        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Column(
            children: [
              _GreenButton(label: 'Use Suggested Route', onTap: onNext),
              const SizedBox(height: 14),
              GestureDetector(
                onTap: () {},
                child: const Text(
                  'Customize Route',
                  textAlign: TextAlign.center,
                  style: TextStyle(color: Color(0xFF888888), fontSize: 14),
                ),
              ),
              const SizedBox(height: 16),
            ],
          ),
        ),
      ],
    );
  }
}

// ─── Step 3: Confirm Route ────────────────────────────────────────────────────
class _Step3 extends StatelessWidget {
  const _Step3({required this.onBack, required this.onNext});
  final VoidCallback onBack, onNext;

  static const _bars = [
    ('The Drunken Duck', 'Start here · 100m · Chill'),
    ('Brewhaus', '150m · Packed'),
    ('Tipsy Tavern', '200m · Loud'),
    ('Downtown Taproom', '350m · Chill'),
    ('Whiskey Barrel', '400m · Packed'),
    ('Night Owl Pub', '500m · Rowdy'),
  ];

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _StepHeader(
            title: 'Confirm Route',
            subtitle: 'Review your bar crawl',
            onBack: onBack,
          ),

          Expanded(
            child: ListView.builder(
              itemCount: _bars.length,
              itemBuilder: (_, i) {
                return _RouteItem(
                  index: i + 1,
                  name: _bars[i].$1,
                  detail: _bars[i].$2,
                  isLast: i == _bars.length - 1,
                );
              },
            ),
          ),

          _GreenButton(label: 'Confirm Route', onTap: onNext),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

class _RouteItem extends StatelessWidget {
  const _RouteItem({required this.index, required this.name, required this.detail, required this.isLast});
  final int index;
  final String name, detail;
  final bool isLast;

  @override
  Widget build(BuildContext context) {
    return IntrinsicHeight(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Left: connector line + dot
          SizedBox(
            width: 36,
            child: Column(
              children: [
                const SizedBox(height: 12),
                // Circle X button
                Container(
                  width: 24,
                  height: 24,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(color: const Color(0xFF555555), width: 1.5),
                    color: const Color(0xFF111118),
                  ),
                  child: const Icon(Icons.close, size: 13, color: Color(0xFF777777)),
                ),
                if (!isLast)
                  Expanded(
                    child: CustomPaint(painter: _DottedLinePainter()),
                  ),
              ],
            ),
          ),

          const SizedBox(width: 12),

          // Right: bar info
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 10),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '$index. $name',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 3),
                  Text(detail, style: const TextStyle(color: Color(0xFF777777), fontSize: 13)),
                  const SizedBox(height: 10),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _DottedLinePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = const Color(0xFF444444)
      ..strokeWidth = 1.5
      ..style = PaintingStyle.stroke;
    const dashH = 4.0;
    const gapH = 4.0;
    double y = 0;
    while (y < size.height) {
      canvas.drawLine(Offset(size.width / 2, y), Offset(size.width / 2, math.min(y + dashH, size.height)), paint);
      y += dashH + gapH;
    }
  }

  @override
  bool shouldRepaint(_DottedLinePainter _) => false;
}

// ─── Step 4: Game Setup ───────────────────────────────────────────────────────
class _Step4 extends StatelessWidget {
  const _Step4({
    required this.difficulty, required this.challengesOn, required this.autoGenerated,
    required this.scoringMode, required this.onDifficultyChanged, required this.onChallengesChanged,
    required this.onAutoGenChanged, required this.onScoringChanged,
    required this.onBack, required this.onStart,
  });

  final String difficulty, scoringMode;
  final bool challengesOn, autoGenerated;
  final ValueChanged<String> onDifficultyChanged, onScoringChanged;
  final ValueChanged<bool> onChallengesChanged, onAutoGenChanged;
  final VoidCallback onBack, onStart;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _StepHeader(
            title: 'Game Setup',
            subtitle: 'Customize your pubgolf game',
            onBack: onBack,
          ),

          const SizedBox(height: 8),

          // Drink Difficulty
          const Text('Drink Difficulty', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          _SegmentedPicker(
            options: const ['Easy', 'Normal', 'Savage'],
            selected: difficulty,
            onChanged: onDifficultyChanged,
          ),

          const SizedBox(height: 28),

          // Challenges
          const Text('Challenges', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          _ToggleRow(
            label: challengesOn ? 'On' : 'Off',
            value: challengesOn,
            onChanged: onChallengesChanged,
            activeColor: const Color(0xFF7CB342),
          ),

          const SizedBox(height: 20),

          // Auto-generated
          _ToggleRow(
            label: 'Auto-generated',
            showInfo: true,
            value: autoGenerated,
            onChanged: onAutoGenChanged,
            activeColor: const Color(0xFFE040FB),
          ),

          const SizedBox(height: 28),

          // Scoring Mode
          const Text('Scoring Mode', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          Row(
            children: [
              Expanded(
                child: _SegmentedPicker(
                  options: const ['Classic', 'Chaos'],
                  selected: scoringMode,
                  onChanged: onScoringChanged,
                ),
              ),
            ],
          ),

          const Spacer(),

          _GreenButton(label: 'Start', onTap: onStart),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

class _SegmentedPicker extends StatelessWidget {
  const _SegmentedPicker({required this.options, required this.selected, required this.onChanged});
  final List<String> options;
  final String selected;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFF2A2A3A)),
      ),
      child: Row(
        children: options.map((o) {
          final isSelected = o == selected;
          return Expanded(
            child: GestureDetector(
              onTap: () => onChanged(o),
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                margin: const EdgeInsets.all(3),
                padding: const EdgeInsets.symmetric(vertical: 10),
                decoration: BoxDecoration(
                  color: isSelected ? const Color(0xFF2A4A10) : Colors.transparent,
                  borderRadius: BorderRadius.circular(8),
                  border: isSelected
                      ? Border.all(color: const Color(0xFF7CB342), width: 1)
                      : null,
                ),
                child: Text(
                  o,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: isSelected ? Colors.white : const Color(0xFF666666),
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                    fontSize: 14,
                  ),
                ),
              ),
            ),
          );
        }).toList(),
      ),
    );
  }
}

class _ToggleRow extends StatelessWidget {
  const _ToggleRow({
    required this.label, required this.value,
    required this.onChanged, required this.activeColor,
    this.showInfo = false,
  });
  final String label;
  final bool value, showInfo;
  final ValueChanged<bool> onChanged;
  final Color activeColor;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFF2A2A3A)),
      ),
      child: Row(
        children: [
          Text(label, style: const TextStyle(color: Colors.white, fontSize: 15)),
          if (showInfo) ...[
            const SizedBox(width: 6),
            const Icon(Icons.info_outline, size: 15, color: Color(0xFF7B2CBF)),
          ],
          const Spacer(),
          Switch(
            value: value,
            onChanged: onChanged,
            activeThumbColor: activeColor,
            activeTrackColor: activeColor.withValues(alpha: 0.3),
            inactiveThumbColor: const Color(0xFF555555),
            inactiveTrackColor: const Color(0xFF222230),
          ),
        ],
      ),
    );
  }
}

// ─── Night map painter ────────────────────────────────────────────────────────
class _NightMapPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final w = size.width;
    final h = size.height;

    // Dark city base
    canvas.drawRect(Rect.fromLTWH(0, 0, w, h),
        Paint()..color = const Color(0xFF080C10));

    // City grid — faint amber street lines
    final roadPaint = Paint()
      ..color = const Color(0x22C87010)
      ..strokeWidth = 1;
    for (double x = 0; x < w; x += w / 12) {
      canvas.drawLine(Offset(x, 0), Offset(x, h), roadPaint);
    }
    for (double y = 0; y < h; y += h / 16) {
      canvas.drawLine(Offset(0, y), Offset(w, y), roadPaint);
    }

    // Warm bokeh city lights
    final blobs = [
      [0.6, 0.15, 60.0, const Color(0x18C87818)],
      [0.75, 0.10, 40.0, const Color(0x16D08010)],
      [0.30, 0.25, 50.0, const Color(0x14B06010)],
      [0.85, 0.30, 35.0, const Color(0x12A05010)],
      [0.50, 0.08, 30.0, const Color(0x18E09018)],
    ];
    for (final b in blobs) {
      canvas.drawCircle(
        Offset((b[0] as double) * w, (b[1] as double) * h),
        b[2] as double,
        Paint()
          ..color = b[3] as Color
          ..maskFilter = MaskFilter.blur(BlurStyle.normal, (b[2] as double) * 0.7),
      );
    }

    // Glowing dotted route path
    final routePoints = [
      Offset(w * 0.50, h * 0.88), // start bottom center
      Offset(w * 0.35, h * 0.72),
      Offset(w * 0.55, h * 0.58),
      Offset(w * 0.30, h * 0.44),
      Offset(w * 0.60, h * 0.30),
      Offset(w * 0.45, h * 0.16),
    ];

    // Glow under path
    final glowPaint = Paint()
      ..color = const Color(0x557CB342)
      ..strokeWidth = 8
      ..style = PaintingStyle.stroke
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 8)
      ..strokeCap = StrokeCap.round;
    for (int i = 0; i < routePoints.length - 1; i++) {
      canvas.drawLine(routePoints[i], routePoints[i + 1], glowPaint);
    }

    // Dotted route line
    final dotPaint = Paint()
      ..color = const Color(0xFF7CB342)
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;
    for (int i = 0; i < routePoints.length - 1; i++) {
      _drawDottedLine(canvas, routePoints[i], routePoints[i + 1], dotPaint);
    }

    // Pin colors
    final pinColors = [
      const Color(0xFFF2C94C), // gold start
      const Color(0xFFEB5757), // red
      const Color(0xFF7CB342), // green
      const Color(0xFF9D4EDD), // purple
      const Color(0xFFEB5757), // red
      const Color(0xFFF2C94C), // gold end
    ];

    for (int i = 0; i < routePoints.length; i++) {
      _drawPin(canvas, routePoints[i], pinColors[i]);
    }
  }

  void _drawDottedLine(Canvas canvas, Offset start, Offset end, Paint paint) {
    final dx = end.dx - start.dx;
    final dy = end.dy - start.dy;
    final dist = math.sqrt(dx * dx + dy * dy);
    final steps = (dist / 10).floor();
    for (int i = 0; i < steps; i += 2) {
      final t0 = i / steps;
      final t1 = (i + 1) / steps;
      canvas.drawLine(
        Offset(start.dx + dx * t0, start.dy + dy * t0),
        Offset(start.dx + dx * t1, start.dy + dy * t1),
        paint,
      );
    }
  }

  void _drawPin(Canvas canvas, Offset pos, Color color) {
    // Glow
    canvas.drawCircle(pos, 14, Paint()
      ..color = color.withValues(alpha: 0.3)
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 10));
    // Circle
    canvas.drawCircle(pos, 9, Paint()..color = color);
    canvas.drawCircle(pos, 9, Paint()
      ..color = Colors.white.withValues(alpha: 0.3)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1.5);
    // Inner dot
    canvas.drawCircle(pos, 3, Paint()..color = Colors.white);
  }

  @override
  bool shouldRepaint(_NightMapPainter _) => false;
}

// ─── Background bokeh for this screen ────────────────────────────────────────
class _NightBokeh extends StatelessWidget {
  const _NightBokeh();

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        gradient: RadialGradient(
          center: Alignment(-0.6, -0.7),
          radius: 0.6,
          colors: [Color(0x16C87010), Colors.transparent],
        ),
      ),
    );
  }
}
