import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'active_hole_screen.dart';
import 'data/bar_model.dart';
import 'data/city_data.dart';

// ─── Entry point ──────────────────────────────────────────────────────────────
class StartNightScreen extends StatefulWidget {
  const StartNightScreen({super.key});

  @override
  State<StartNightScreen> createState() => _StartNightScreenState();
}

class _StartNightScreenState extends State<StartNightScreen> {
  final PageController _pageController = PageController();
  int _currentPage = 0;

  // Shared state across steps
  String nightName = '';
  double numBars = 6;
  String vibe = 'Competitive';
  String difficulty = 'Normal';
  bool challengesOn = true;
  bool autoGenerated = true;
  String scoringMode = 'Chaos';
  CityInfo? selectedCity;

  void _next() {
    if (_currentPage < 3) {
      _pageController.nextPage(
        duration: const Duration(milliseconds: 350),
        curve: Curves.easeInOut,
      );
    }
  }

  void _back() {
    if (_currentPage == 0) {
      Navigator.pop(context);
    } else {
      _pageController.previousPage(
        duration: const Duration(milliseconds: 350),
        curve: Curves.easeInOut,
      );
    }
  }

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFF060608),
      body: Stack(
        children: [
          // Background — same style as home
          Container(
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topCenter,
                end: Alignment.bottomCenter,
                colors: [Color(0xFF0B1A14), Color(0xFF060608)],
              ),
            ),
          ),
          const _NightBokeh(),
          Container(
            decoration: const BoxDecoration(
              gradient: RadialGradient(
                center: Alignment(0.0, 0.5),
                radius: 0.7,
                colors: [Color(0x1E7B2CBF), Colors.transparent],
              ),
            ),
          ),

          // Pages
          SafeArea(
            child: Column(
              children: [
                Expanded(
                  child: PageView(
                    controller: _pageController,
                    physics: const NeverScrollableScrollPhysics(),
                    onPageChanged: (i) => setState(() => _currentPage = i),
                    children: [
                      _Step1(
                        nightName: nightName,
                        numBars: numBars,
                        vibe: vibe,
                        onNameChanged: (v) => setState(() => nightName = v),
                        onBarsChanged: (v) => setState(() => numBars = v),
                        onVibeChanged: (v) => setState(() => vibe = v),
                        onBack: _back,
                        onNext: _next,
                      ),
                      _Step2(
                        onBack: _back,
                        onNext: _next,
                        selectedCity: selectedCity,
                        onCityChanged: (c) => setState(() => selectedCity = c),
                      ),
                      _Step3(
                        onBack: _back,
                        onNext: _next,
                        numBars: numBars.round(),
                        selectedCity: selectedCity,
                      ),
                      _Step4(
                        difficulty: difficulty,
                        challengesOn: challengesOn,
                        autoGenerated: autoGenerated,
                        scoringMode: scoringMode,
                        onDifficultyChanged: (v) => setState(() => difficulty = v),
                        onChallengesChanged: (v) => setState(() => challengesOn = v),
                        onAutoGenChanged: (v) => setState(() => autoGenerated = v),
                        onScoringChanged: (v) => setState(() => scoringMode = v),
                        onBack: _back,
                        onStart: () => Navigator.pushReplacement(
                          context,
                          MaterialPageRoute(builder: (_) => ActiveHoleScreen(numHoles: numBars.round())),
                        ),
                      ),
                    ],
                  ),
                ),

                // Page dots
                Padding(
                  padding: const EdgeInsets.only(bottom: 20),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: List.generate(4, (i) {
                      final active = i == _currentPage;
                      return AnimatedContainer(
                        duration: const Duration(milliseconds: 250),
                        margin: const EdgeInsets.symmetric(horizontal: 4),
                        width: active ? 18 : 6,
                        height: 6,
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(3),
                          color: active
                              ? const Color(0xFF7CB342)
                              : const Color(0xFF333333),
                        ),
                      );
                    }),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─── Shared widgets ───────────────────────────────────────────────────────────

class _StepHeader extends StatelessWidget {
  const _StepHeader({required this.title, required this.subtitle, required this.onBack});
  final String title, subtitle;
  final VoidCallback onBack;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(8, 12, 16, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              IconButton(
                icon: const Icon(Icons.arrow_back_ios, color: Colors.white, size: 20),
                onPressed: onBack,
              ),
              Text(
                title,
                style: const TextStyle(
                  color: Colors.white,
                  fontSize: 24,
                  fontWeight: FontWeight.w800,
                ),
              ),
            ],
          ),
          Padding(
            padding: const EdgeInsets.only(left: 16),
            child: Text(
              subtitle,
              style: const TextStyle(color: Color(0xFF888888), fontSize: 13),
            ),
          ),
          const SizedBox(height: 8),
        ],
      ),
    );
  }
}

// ─── Green CTA button with press-scale animation ──────────────────────────────
class _GreenButton extends StatefulWidget {
  const _GreenButton({required this.label, required this.onTap});
  final String label;
  final VoidCallback onTap;

  @override
  State<_GreenButton> createState() => _GreenButtonState();
}

class _GreenButtonState extends State<_GreenButton>
    with SingleTickerProviderStateMixin {
  late final AnimationController _ctrl;
  late final Animation<double> _scale;

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 60),
      reverseDuration: const Duration(milliseconds: 320),
    );
    _scale = Tween<double>(begin: 1.0, end: 0.97).animate(
      CurvedAnimation(
        parent: _ctrl,
        curve: Curves.easeInOut,
        reverseCurve: Curves.elasticOut,
      ),
    );
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTapDown: (_) => _ctrl.forward(),
      onTapUp: (_) {
        _ctrl.reverse();
        widget.onTap();
      },
      onTapCancel: () => _ctrl.reverse(),
      child: ScaleTransition(
        scale: _scale,
        child: Container(
          width: double.infinity,
          padding: const EdgeInsets.symmetric(vertical: 17),
          decoration: BoxDecoration(
            color: const Color(0xFF1A2A0A),
            borderRadius: BorderRadius.circular(14),
            border: Border.all(color: const Color(0xFF7CB342), width: 1.5),
            boxShadow: const [
              BoxShadow(color: Color(0x667CB342), blurRadius: 18, spreadRadius: 2),
              BoxShadow(color: Color(0x337CB342), blurRadius: 36, spreadRadius: 4),
            ],
          ),
          child: Text(
            widget.label,
            textAlign: TextAlign.center,
            style: const TextStyle(
              color: Colors.white,
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
      ),
    );
  }
}

class _DarkField extends StatelessWidget {
  const _DarkField({required this.hint, required this.onChanged, this.initialValue = ''});
  final String hint, initialValue;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    return TextFormField(
      initialValue: initialValue,
      onChanged: onChanged,
      style: const TextStyle(color: Colors.white, fontSize: 16),
      decoration: InputDecoration(
        hintText: hint,
        hintStyle: const TextStyle(color: Color(0xFF555555)),
        filled: true,
        fillColor: const Color(0xFF111118),
        contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Color(0xFF2A2A3A), width: 1),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10),
          borderSide: const BorderSide(color: Color(0xFF7B2CBF), width: 1.5),
        ),
      ),
    );
  }
}

// ─── Step 1: Create Your Night — staggered entrance animation ─────────────────
class _Step1 extends StatefulWidget {
  const _Step1({
    required this.nightName, required this.numBars, required this.vibe,
    required this.onNameChanged, required this.onBarsChanged, required this.onVibeChanged,
    required this.onBack, required this.onNext,
  });

  final String nightName, vibe;
  final double numBars;
  final ValueChanged<String> onNameChanged, onVibeChanged;
  final ValueChanged<double> onBarsChanged;
  final VoidCallback onBack, onNext;

  @override
  State<_Step1> createState() => _Step1State();
}

class _Step1State extends State<_Step1> with SingleTickerProviderStateMixin {
  late final AnimationController _ctrl;

  // Each section: fade + upward slide
  late final Animation<double> _headerOpacity;
  late final Animation<Offset> _headerOffset;
  late final Animation<double> _nameOpacity;
  late final Animation<Offset> _nameOffset;
  late final Animation<double> _barsOpacity;
  late final Animation<Offset> _barsOffset;
  late final Animation<double> _vibeOpacity;
  late final Animation<Offset> _vibeOffset;
  late final Animation<double> _ctaOpacity;
  late final Animation<Offset> _ctaOffset;

  static Animation<double> _fadeInterval(
      AnimationController c, double start, double end) {
    return CurvedAnimation(
        parent: c, curve: Interval(start, end, curve: Curves.easeOut));
  }

  static Animation<Offset> _slideInterval(
      AnimationController c, double start, double end,
      {bool fromBelow = false}) {
    return Tween<Offset>(
      begin: Offset(0, fromBelow ? 0.08 : -0.12),
      end: Offset.zero,
    ).animate(CurvedAnimation(
        parent: c, curve: Interval(start, end, curve: Curves.easeOut)));
  }

  @override
  void initState() {
    super.initState();
    _ctrl = AnimationController(
        vsync: this, duration: const Duration(milliseconds: 680));

    // Stagger: header → name → bars → vibe → cta
    _headerOpacity = _fadeInterval(_ctrl, 0.00, 0.44);
    _headerOffset  = _slideInterval(_ctrl, 0.00, 0.44);
    _nameOpacity   = _fadeInterval(_ctrl, 0.12, 0.56);
    _nameOffset    = _slideInterval(_ctrl, 0.12, 0.56);
    _barsOpacity   = _fadeInterval(_ctrl, 0.26, 0.70);
    _barsOffset    = _slideInterval(_ctrl, 0.26, 0.70);
    _vibeOpacity   = _fadeInterval(_ctrl, 0.40, 0.84);
    _vibeOffset    = _slideInterval(_ctrl, 0.40, 0.84);
    _ctaOpacity    = _fadeInterval(_ctrl, 0.56, 1.00);
    _ctaOffset     = _slideInterval(_ctrl, 0.56, 1.00, fromBelow: true);

    _ctrl.forward();
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  Widget _animated(
      Animation<double> fade, Animation<Offset> slide, Widget child) {
    return FadeTransition(
      opacity: fade,
      child: SlideTransition(position: slide, child: child),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Header
          _animated(
            _headerOpacity, _headerOffset,
            _StepHeader(
              title: 'Create Your Night',
              subtitle: 'Night Name · Optional',
              onBack: widget.onBack,
            ),
          ),
          const SizedBox(height: 16),

          // Night Name section
          _animated(
            _nameOpacity, _nameOffset,
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Night Name',
                    style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
                const SizedBox(height: 8),
                _DarkField(
                  hint: "John's Birthday Run",
                  initialValue: widget.nightName,
                  onChanged: widget.onNameChanged,
                ),
                const SizedBox(height: 6),
                const Text('Name your pub crawl',
                    style: TextStyle(color: Color(0xFF555555), fontSize: 12)),
              ],
            ),
          ),

          const SizedBox(height: 28),

          // Bars section
          _animated(
            _barsOpacity, _barsOffset,
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Number of Bars',
                    style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
                const SizedBox(height: 12),
                _BarsSlider(value: widget.numBars, onChanged: widget.onBarsChanged),
              ],
            ),
          ),

          const SizedBox(height: 28),

          // Vibe section
          _animated(
            _vibeOpacity, _vibeOffset,
            Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Text('Vibe',
                    style: TextStyle(color: Colors.white, fontSize: 15, fontWeight: FontWeight.w600)),
                const SizedBox(height: 10),
                _VibePicker(selected: widget.vibe, onChanged: widget.onVibeChanged),
              ],
            ),
          ),

          const Spacer(),

          // CTA — slides up from below
          _animated(
            _ctaOpacity, _ctaOffset,
            _GreenButton(label: 'Continue', onTap: widget.onNext),
          ),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

// ─── Bar count slider — haptic on each integer step ───────────────────────────
class _BarsSlider extends StatelessWidget {
  const _BarsSlider({required this.value, required this.onChanged});
  final double value;
  final ValueChanged<double> onChanged;

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        SliderTheme(
          data: SliderTheme.of(context).copyWith(
            trackHeight: 4,
            activeTrackColor: const Color(0xFF7CB342),
            inactiveTrackColor: const Color(0xFF2A2A3A),
            thumbColor: Colors.white,
            thumbShape: _BubbleThumbShape(value.round()),
            overlayColor: const Color(0x227CB342),
          ),
          child: Slider(
            value: value,
            min: 3,
            max: 9,
            divisions: 6,
            onChanged: (v) {
              if (v.round() != value.round()) {
                HapticFeedback.lightImpact();
              }
              onChanged(v);
            },
          ),
        ),
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 4),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: const [
              Text('3', style: TextStyle(color: Color(0xFF555555), fontSize: 12)),
              Text('9', style: TextStyle(color: Color(0xFF555555), fontSize: 12)),
            ],
          ),
        ),
      ],
    );
  }
}

class _BubbleThumbShape extends SliderComponentShape {
  final int value;
  const _BubbleThumbShape(this.value);

  @override
  Size getPreferredSize(bool isEnabled, bool isDiscrete) => const Size(28, 28);

  @override
  void paint(PaintingContext context, Offset center, {required Animation<double> activationAnimation,
    required Animation<double> enableAnimation, required bool isDiscrete,
    required TextPainter labelPainter, required RenderBox parentBox,
    required SliderThemeData sliderTheme, required TextDirection textDirection,
    required double value, required double textScaleFactor, required Size sizeWithOverflow}) {
    final canvas = context.canvas;
    canvas.drawCircle(center, 14, Paint()..color = const Color(0xFF7CB342));
    canvas.drawCircle(center, 14, Paint()..color = Colors.white..style = PaintingStyle.stroke..strokeWidth = 2);
    final tp = TextPainter(
      text: TextSpan(text: this.value.toString(),
          style: const TextStyle(color: Colors.white, fontSize: 11, fontWeight: FontWeight.bold)),
      textDirection: TextDirection.ltr,
    )..layout();
    tp.paint(canvas, center - Offset(tp.width / 2, tp.height / 2));
  }
}

// ─── Vibe picker — scale bounce + haptic on selection ─────────────────────────
class _VibePicker extends StatelessWidget {
  const _VibePicker({required this.selected, required this.onChanged});
  final String selected;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    final options = ['Chill', 'Competitive', '😊'];
    return Row(
      children: options.map((o) {
        final isSelected = o == selected;
        return Padding(
          padding: const EdgeInsets.only(right: 10),
          child: GestureDetector(
            onTap: () {
              HapticFeedback.lightImpact();
              onChanged(o);
            },
            child: AnimatedScale(
              scale: isSelected ? 1.05 : 1.0,
              duration: const Duration(milliseconds: 220),
              curve: Curves.easeOut,
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                decoration: BoxDecoration(
                  color: isSelected ? const Color(0xFF7B2CBF) : const Color(0xFF111118),
                  borderRadius: BorderRadius.circular(22),
                  border: Border.all(
                    color: isSelected ? const Color(0xFF9D4EDD) : const Color(0xFF2A2A3A),
                    width: 1.5,
                  ),
                  boxShadow: isSelected ? const [
                    BoxShadow(color: Color(0x559D4EDD), blurRadius: 16, spreadRadius: 2),
                  ] : null,
                ),
                child: Text(
                  o,
                  style: TextStyle(
                    color: isSelected ? Colors.white : const Color(0xFF777777),
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                    fontSize: 14,
                  ),
                ),
              ),
            ),
          ),
        );
      }).toList(),
    );
  }
}

// ─── Step 2: Pick Your Area ───────────────────────────────────────────────────
class _Step2 extends StatefulWidget {
  const _Step2({
    required this.onBack,
    required this.onNext,
    required this.selectedCity,
    required this.onCityChanged,
  });
  final VoidCallback onBack, onNext;
  final CityInfo? selectedCity;
  final ValueChanged<CityInfo> onCityChanged;

  @override
  State<_Step2> createState() => _Step2State();
}

class _Step2State extends State<_Step2> {
  final _searchController = TextEditingController();
  String _query = '';

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  List<CityInfo> get _filtered {
    if (_query.isEmpty) return kSupportedCities;
    final q = _query.toLowerCase();
    return kSupportedCities.where((c) => c.name.toLowerCase().contains(q)).toList();
  }

  void _showVoteSheet(BuildContext context) {
    HapticFeedback.mediumImpact();
    showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => _VoteSheet(city: widget.selectedCity),
    );
  }

  @override
  Widget build(BuildContext context) {
    final city = widget.selectedCity;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: _StepHeader(
            title: 'Pick Your Area',
            subtitle: 'Select a city to crawl',
            onBack: widget.onBack,
          ),
        ),

        // ── Search bar ────────────────────────────────────────────────────
        Padding(
          padding: const EdgeInsets.fromLTRB(20, 0, 20, 12),
          child: TextField(
            controller: _searchController,
            onChanged: (v) => setState(() => _query = v),
            style: const TextStyle(color: Colors.white, fontSize: 15),
            decoration: InputDecoration(
              hintText: 'Search city…',
              hintStyle: const TextStyle(color: Color(0xFF555555)),
              prefixIcon: const Icon(Icons.search, color: Color(0xFF555555), size: 20),
              filled: true,
              fillColor: const Color(0xFF111118),
              contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              border: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: BorderSide.none,
              ),
              enabledBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFF2A2A3A), width: 1),
              ),
              focusedBorder: OutlineInputBorder(
                borderRadius: BorderRadius.circular(12),
                borderSide: const BorderSide(color: Color(0xFF7B2CBF), width: 1.5),
              ),
            ),
          ),
        ),

        // ── City list ─────────────────────────────────────────────────────
        SizedBox(
          height: 56,
          child: ListView.builder(
            scrollDirection: Axis.horizontal,
            padding: const EdgeInsets.symmetric(horizontal: 20),
            itemCount: _filtered.length,
            itemBuilder: (_, i) {
              final c = _filtered[i];
              final selected = city?.name == c.name;
              return GestureDetector(
                onTap: () {
                  HapticFeedback.lightImpact();
                  widget.onCityChanged(c);
                  setState(() {});
                },
                child: AnimatedContainer(
                  duration: const Duration(milliseconds: 200),
                  margin: const EdgeInsets.only(right: 10),
                  padding: const EdgeInsets.symmetric(horizontal: 18, vertical: 10),
                  decoration: BoxDecoration(
                    color: selected ? const Color(0xFF1A2A0A) : const Color(0xFF111118),
                    borderRadius: BorderRadius.circular(28),
                    border: Border.all(
                      color: selected ? const Color(0xFF7CB342) : const Color(0xFF2A2A3A),
                      width: 1.5,
                    ),
                    boxShadow: selected ? const [
                      BoxShadow(color: Color(0x447CB342), blurRadius: 12, spreadRadius: 1),
                    ] : null,
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Text(c.emoji, style: const TextStyle(fontSize: 16)),
                      const SizedBox(width: 8),
                      Text(
                        c.name,
                        style: TextStyle(
                          color: selected ? Colors.white : const Color(0xFF888888),
                          fontWeight: selected ? FontWeight.bold : FontWeight.normal,
                          fontSize: 14,
                        ),
                      ),
                    ],
                  ),
                ),
              );
            },
          ),
        ),

        const SizedBox(height: 12),

        // ── Map ───────────────────────────────────────────────────────────
        Expanded(
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 20),
            child: Stack(
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(16),
                  child: CustomPaint(
                    painter: _NightMapPainter(),
                    child: Container(),
                  ),
                ),
                // City label overlay
                if (city != null)
                  Positioned(
                    top: 14,
                    left: 14,
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                      decoration: BoxDecoration(
                        color: const Color(0xDD0B1A14),
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(color: const Color(0xFF7CB342), width: 1),
                      ),
                      child: Row(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Text(city.emoji, style: const TextStyle(fontSize: 14)),
                          const SizedBox(width: 6),
                          Text(
                            city.name,
                            style: const TextStyle(
                              color: Colors.white,
                              fontSize: 13,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                          const SizedBox(width: 6),
                          Text(
                            '${city.bars.length} bars',
                            style: const TextStyle(color: Color(0xFF7CB342), fontSize: 12),
                          ),
                        ],
                      ),
                    ),
                  ),
                // Route chip
                Positioned(
                  bottom: 14,
                  left: 0,
                  right: 0,
                  child: Center(
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                      decoration: BoxDecoration(
                        color: const Color(0xCC111118),
                        borderRadius: BorderRadius.circular(22),
                        border: Border.all(color: const Color(0xFF2A2A3A)),
                      ),
                      child: Text(
                        city == null
                            ? 'Select a city above ↑'
                            : 'Optimised route generated ✦',
                        style: const TextStyle(color: Colors.white, fontSize: 13),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),
        ),

        const SizedBox(height: 16),

        Padding(
          padding: const EdgeInsets.symmetric(horizontal: 20),
          child: Column(
            children: [
              _GreenButton(
                label: 'Use Suggested Route',
                onTap: city == null ? () {} : widget.onNext,
              ),
              const SizedBox(height: 14),
              GestureDetector(
                onTap: city == null ? null : () => _showVoteSheet(context),
                child: Text(
                  'Customize Route',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: city == null ? const Color(0xFF444444) : const Color(0xFF888888),
                    fontSize: 14,
                  ),
                ),
              ),
              const SizedBox(height: 16),
            ],
          ),
        ),
      ],
    );
  }
}

// ─── Vote Sheet ───────────────────────────────────────────────────────────────
class _VoteSheet extends StatefulWidget {
  const _VoteSheet({required this.city});
  final CityInfo? city;

  @override
  State<_VoteSheet> createState() => _VoteSheetState();
}

class _VoteSheetState extends State<_VoteSheet> {
  // barName → upvote count (this session only; would sync via backend later)
  final Map<String, int> _votes = {};

  List<({String name, String neighborhood, String vibe, int votes})> get _sorted {
    final bars = widget.city?.bars ?? [];
    final items = bars.map((b) => (
      name: b.name,
      neighborhood: b.neighborhood,
      vibe: b.vibe,
      votes: _votes[b.name] ?? 0,
    )).toList();
    items.sort((a, b) => b.votes.compareTo(a.votes));
    return items;
  }

  @override
  Widget build(BuildContext context) {
    final city = widget.city;
    return DraggableScrollableSheet(
      initialChildSize: 0.75,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      builder: (_, scrollController) => Container(
        decoration: const BoxDecoration(
          color: Color(0xFF0E1A12),
          borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
          border: Border(top: BorderSide(color: Color(0xFF2A2A3A))),
        ),
        child: Column(
          children: [
            // Handle
            Container(
              width: 40, height: 4,
              margin: const EdgeInsets.only(top: 12, bottom: 16),
              decoration: BoxDecoration(
                color: const Color(0xFF444444),
                borderRadius: BorderRadius.circular(2),
              ),
            ),

            // Header
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 0, 20, 4),
              child: Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const Text(
                          'Vote Your Route',
                          style: TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.bold),
                        ),
                        const SizedBox(height: 2),
                        Text(
                          city == null ? 'No city selected' : '${city.name} · Upvote the bars you want',
                          style: const TextStyle(color: Color(0xFF888888), fontSize: 13),
                        ),
                      ],
                    ),
                  ),
                  // Total votes badge
                  Container(
                    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                    decoration: BoxDecoration(
                      color: const Color(0xFF1A2A0A),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(color: const Color(0xFF7CB342), width: 1),
                    ),
                    child: Text(
                      '${_votes.values.fold(0, (a, b) => a + b)} votes',
                      style: const TextStyle(color: Color(0xFF7CB342), fontSize: 12, fontWeight: FontWeight.bold),
                    ),
                  ),
                ],
              ),
            ),

            const Divider(color: Color(0xFF1E1E1E), height: 20),

            // Bar list
            Expanded(
              child: ListView.builder(
                controller: scrollController,
                padding: const EdgeInsets.symmetric(horizontal: 20),
                itemCount: _sorted.length,
                itemBuilder: (_, i) {
                  final bar = _sorted[i];
                  final hasVote = (_votes[bar.name] ?? 0) > 0;
                  return Container(
                    margin: const EdgeInsets.only(bottom: 10),
                    padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                    decoration: BoxDecoration(
                      color: hasVote ? const Color(0xFF111A0A) : const Color(0xFF111118),
                      borderRadius: BorderRadius.circular(12),
                      border: Border.all(
                        color: hasVote ? const Color(0xFF4A7A22) : const Color(0xFF2A2A3A),
                        width: 1,
                      ),
                    ),
                    child: Row(
                      children: [
                        // Rank badge
                        Container(
                          width: 28, height: 28,
                          alignment: Alignment.center,
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: i == 0 && bar.votes > 0
                                ? const Color(0xFFF2C94C).withValues(alpha: 0.15)
                                : const Color(0xFF1E1E1E),
                            border: Border.all(
                              color: i == 0 && bar.votes > 0
                                  ? const Color(0xFFF2C94C)
                                  : const Color(0xFF333333),
                            ),
                          ),
                          child: Text(
                            '${i + 1}',
                            style: TextStyle(
                              color: i == 0 && bar.votes > 0
                                  ? const Color(0xFFF2C94C)
                                  : const Color(0xFF666666),
                              fontSize: 11,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ),
                        const SizedBox(width: 12),

                        // Name + neighborhood
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                bar.name,
                                style: const TextStyle(
                                  color: Colors.white,
                                  fontSize: 14,
                                  fontWeight: FontWeight.w600,
                                ),
                              ),
                              Text(
                                '${bar.neighborhood} · ${bar.vibe}',
                                style: const TextStyle(color: Color(0xFF777777), fontSize: 12),
                              ),
                            ],
                          ),
                        ),

                        // Vote count
                        if (bar.votes > 0)
                          Padding(
                            padding: const EdgeInsets.only(right: 10),
                            child: Text(
                              '+${bar.votes}',
                              style: const TextStyle(
                                color: Color(0xFF7CB342),
                                fontSize: 13,
                                fontWeight: FontWeight.bold,
                              ),
                            ),
                          ),

                        // Upvote button
                        GestureDetector(
                          onTap: () {
                            HapticFeedback.lightImpact();
                            setState(() {
                              _votes[bar.name] = (_votes[bar.name] ?? 0) + 1;
                            });
                          },
                          child: AnimatedContainer(
                            duration: const Duration(milliseconds: 180),
                            width: 36, height: 36,
                            decoration: BoxDecoration(
                              shape: BoxShape.circle,
                              color: hasVote
                                  ? const Color(0xFF7CB342).withValues(alpha: 0.2)
                                  : const Color(0xFF1E1E1E),
                              border: Border.all(
                                color: hasVote ? const Color(0xFF7CB342) : const Color(0xFF333333),
                              ),
                            ),
                            child: Icon(
                              Icons.keyboard_arrow_up_rounded,
                              color: hasVote ? const Color(0xFF7CB342) : const Color(0xFF555555),
                              size: 22,
                            ),
                          ),
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),

            // Confirm button
            Padding(
              padding: EdgeInsets.fromLTRB(20, 8, 20, MediaQuery.of(context).padding.bottom + 16),
              child: _GreenButton(
                label: 'Confirm Voted Route',
                onTap: () => Navigator.pop(context),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ─── Step 3: Confirm Route ────────────────────────────────────────────────────
class _Step3 extends StatelessWidget {
  const _Step3({
    required this.onBack,
    required this.onNext,
    required this.numBars,
    required this.selectedCity,
  });
  final VoidCallback onBack, onNext;
  final int numBars;
  final CityInfo? selectedCity;

  // Fallback bars if no city is selected yet
  static const _fallbackBars = [
    (name: 'The Drunken Duck', detail: 'Start here · Chill'),
    (name: 'Brewhaus',          detail: 'Packed'),
    (name: 'Tipsy Tavern',      detail: 'Loud'),
    (name: 'Downtown Taproom',  detail: 'Chill'),
    (name: 'Whiskey Barrel',    detail: 'Packed'),
    (name: 'Night Owl Pub',     detail: 'Rowdy'),
    (name: 'The Rusty Nail',    detail: 'Lively'),
    (name: 'Crown & Anchor',    detail: 'Chill'),
    (name: 'The Fox & Hound',   detail: 'Rowdy'),
  ];

  @override
  Widget build(BuildContext context) {
    // Use nearest-neighbour optimized route from selected city, else fallback
    final List<({String name, String detail})> bars;
    if (selectedCity != null) {
      final route = nearestNeighborRoute(selectedCity!.bars, numBars);
      bars = route.map((b) => (name: b.name, detail: '${b.neighborhood} · ${b.vibe}')).toList();
    } else {
      bars = _fallbackBars.take(numBars).toList();
    }

    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _StepHeader(
            title: 'Confirm Route',
            subtitle: selectedCity == null
                ? 'Review your bar crawl'
                : '${selectedCity!.name} · Optimised for least distance',
            onBack: onBack,
          ),

          Expanded(
            child: ListView.builder(
              itemCount: bars.length,
              itemBuilder: (_, i) {
                return _RouteItem(
                  index: i + 1,
                  name: bars[i].name,
                  detail: bars[i].detail,
                  isLast: i == bars.length - 1,
                );
              },
            ),
          ),

          _GreenButton(label: 'Confirm Route', onTap: onNext),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

class _RouteItem extends StatelessWidget {
  const _RouteItem({required this.index, required this.name, required this.detail, required this.isLast});
  final int index;
  final String name, detail;
  final bool isLast;

  @override
  Widget build(BuildContext context) {
    return IntrinsicHeight(
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          // Left: connector line + dot
          SizedBox(
            width: 36,
            child: Column(
              children: [
                const SizedBox(height: 12),
                // Circle X button
                Container(
                  width: 24,
                  height: 24,
                  decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(color: const Color(0xFF555555), width: 1.5),
                    color: const Color(0xFF111118),
                  ),
                  child: const Icon(Icons.close, size: 13, color: Color(0xFF777777)),
                ),
                if (!isLast)
                  Expanded(
                    child: CustomPaint(painter: _DottedLinePainter()),
                  ),
              ],
            ),
          ),

          const SizedBox(width: 12),

          // Right: bar info
          Expanded(
            child: Padding(
              padding: const EdgeInsets.symmetric(vertical: 10),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    '$index. $name',
                    style: const TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                  const SizedBox(height: 3),
                  Text(detail, style: const TextStyle(color: Color(0xFF777777), fontSize: 13)),
                  const SizedBox(height: 10),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _DottedLinePainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final paint = Paint()
      ..color = const Color(0xFF444444)
      ..strokeWidth = 1.5
      ..style = PaintingStyle.stroke;
    const dashH = 4.0;
    const gapH = 4.0;
    double y = 0;
    while (y < size.height) {
      canvas.drawLine(Offset(size.width / 2, y), Offset(size.width / 2, math.min(y + dashH, size.height)), paint);
      y += dashH + gapH;
    }
  }

  @override
  bool shouldRepaint(_DottedLinePainter _) => false;
}

// ─── Step 4: Game Setup ───────────────────────────────────────────────────────
class _Step4 extends StatelessWidget {
  const _Step4({
    required this.difficulty, required this.challengesOn, required this.autoGenerated,
    required this.scoringMode, required this.onDifficultyChanged, required this.onChallengesChanged,
    required this.onAutoGenChanged, required this.onScoringChanged,
    required this.onBack, required this.onStart,
  });

  final String difficulty, scoringMode;
  final bool challengesOn, autoGenerated;
  final ValueChanged<String> onDifficultyChanged, onScoringChanged;
  final ValueChanged<bool> onChallengesChanged, onAutoGenChanged;
  final VoidCallback onBack, onStart;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _StepHeader(
            title: 'Game Setup',
            subtitle: 'Customize your pubgolf game',
            onBack: onBack,
          ),

          const SizedBox(height: 8),

          // Drink Difficulty
          const Text('Drink Difficulty', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          _SegmentedPicker(
            options: const ['Easy', 'Normal', 'Savage'],
            selected: difficulty,
            onChanged: onDifficultyChanged,
          ),

          const SizedBox(height: 28),

          // Challenges
          const Text('Challenges', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          _ToggleRow(
            label: challengesOn ? 'On' : 'Off',
            value: challengesOn,
            onChanged: onChallengesChanged,
            activeColor: const Color(0xFF7CB342),
          ),

          const SizedBox(height: 20),

          // Auto-generated
          _ToggleRow(
            label: 'Auto-generated',
            showInfo: true,
            value: autoGenerated,
            onChanged: onAutoGenChanged,
            activeColor: const Color(0xFFE040FB),
          ),

          const SizedBox(height: 28),

          // Scoring Mode
          const Text('Scoring Mode', style: TextStyle(color: Colors.white, fontSize: 16, fontWeight: FontWeight.w600)),
          const SizedBox(height: 10),
          Row(
            children: [
              Expanded(
                child: _SegmentedPicker(
                  options: const ['Classic', 'Chaos'],
                  selected: scoringMode,
                  onChanged: onScoringChanged,
                ),
              ),
            ],
          ),

          const Spacer(),

          _GreenButton(label: 'Start', onTap: onStart),
          const SizedBox(height: 16),
        ],
      ),
    );
  }
}

class _SegmentedPicker extends StatelessWidget {
  const _SegmentedPicker({required this.options, required this.selected, required this.onChanged});
  final List<String> options;
  final String selected;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFF2A2A3A)),
      ),
      child: Row(
        children: options.map((o) {
          final isSelected = o == selected;
          return Expanded(
            child: GestureDetector(
              onTap: () {
                HapticFeedback.lightImpact();
                onChanged(o);
              },
              child: AnimatedContainer(
                duration: const Duration(milliseconds: 200),
                margin: const EdgeInsets.all(3),
                padding: const EdgeInsets.symmetric(vertical: 10),
                decoration: BoxDecoration(
                  color: isSelected ? const Color(0xFF2A4A10) : Colors.transparent,
                  borderRadius: BorderRadius.circular(8),
                  border: isSelected
                      ? Border.all(color: const Color(0xFF7CB342), width: 1)
                      : null,
                ),
                child: Text(
                  o,
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: isSelected ? Colors.white : const Color(0xFF666666),
                    fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                    fontSize: 14,
                  ),
                ),
              ),
            ),
          );
        }).toList(),
      ),
    );
  }
}

class _ToggleRow extends StatelessWidget {
  const _ToggleRow({
    required this.label, required this.value,
    required this.onChanged, required this.activeColor,
    this.showInfo = false,
  });
  final String label;
  final bool value, showInfo;
  final ValueChanged<bool> onChanged;
  final Color activeColor;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: const Color(0xFF111118),
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: const Color(0xFF2A2A3A)),
      ),
      child: Row(
        children: [
          Text(label, style: const TextStyle(color: Colors.white, fontSize: 15)),
          if (showInfo) ...[
            const SizedBox(width: 6),
            const Icon(Icons.info_outline, size: 15, color: Color(0xFF7B2CBF)),
          ],
          const Spacer(),
          Switch(
            value: value,
            onChanged: onChanged,
            activeThumbColor: activeColor,
            activeTrackColor: activeColor.withValues(alpha: 0.3),
            inactiveThumbColor: const Color(0xFF555555),
            inactiveTrackColor: const Color(0xFF222230),
          ),
        ],
      ),
    );
  }
}

// ─── Night map painter ────────────────────────────────────────────────────────
class _NightMapPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final w = size.width;
    final h = size.height;

    // Dark city base
    canvas.drawRect(Rect.fromLTWH(0, 0, w, h),
        Paint()..color = const Color(0xFF080C10));

    // City grid — faint amber street lines
    final roadPaint = Paint()
      ..color = const Color(0x22C87010)
      ..strokeWidth = 1;
    for (double x = 0; x < w; x += w / 12) {
      canvas.drawLine(Offset(x, 0), Offset(x, h), roadPaint);
    }
    for (double y = 0; y < h; y += h / 16) {
      canvas.drawLine(Offset(0, y), Offset(w, y), roadPaint);
    }

    // Warm bokeh city lights
    final blobs = [
      [0.6, 0.15, 60.0, const Color(0x18C87818)],
      [0.75, 0.10, 40.0, const Color(0x16D08010)],
      [0.30, 0.25, 50.0, const Color(0x14B06010)],
      [0.85, 0.30, 35.0, const Color(0x12A05010)],
      [0.50, 0.08, 30.0, const Color(0x18E09018)],
    ];
    for (final b in blobs) {
      canvas.drawCircle(
        Offset((b[0] as double) * w, (b[1] as double) * h),
        b[2] as double,
        Paint()
          ..color = b[3] as Color
          ..maskFilter = MaskFilter.blur(BlurStyle.normal, (b[2] as double) * 0.7),
      );
    }

    // Glowing dotted route path
    final routePoints = [
      Offset(w * 0.50, h * 0.88),
      Offset(w * 0.35, h * 0.72),
      Offset(w * 0.55, h * 0.58),
      Offset(w * 0.30, h * 0.44),
      Offset(w * 0.60, h * 0.30),
      Offset(w * 0.45, h * 0.16),
    ];

    // Glow under path
    final glowPaint = Paint()
      ..color = const Color(0x557CB342)
      ..strokeWidth = 8
      ..style = PaintingStyle.stroke
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 8)
      ..strokeCap = StrokeCap.round;
    for (int i = 0; i < routePoints.length - 1; i++) {
      canvas.drawLine(routePoints[i], routePoints[i + 1], glowPaint);
    }

    // Dotted route line
    final dotPaint = Paint()
      ..color = const Color(0xFF7CB342)
      ..strokeWidth = 2
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.round;
    for (int i = 0; i < routePoints.length - 1; i++) {
      _drawDottedLine(canvas, routePoints[i], routePoints[i + 1], dotPaint);
    }

    // Pin colors
    final pinColors = [
      const Color(0xFFF2C94C),
      const Color(0xFFEB5757),
      const Color(0xFF7CB342),
      const Color(0xFF9D4EDD),
      const Color(0xFFEB5757),
      const Color(0xFFF2C94C),
    ];

    for (int i = 0; i < routePoints.length; i++) {
      _drawPin(canvas, routePoints[i], pinColors[i]);
    }
  }

  void _drawDottedLine(Canvas canvas, Offset start, Offset end, Paint paint) {
    final dx = end.dx - start.dx;
    final dy = end.dy - start.dy;
    final dist = math.sqrt(dx * dx + dy * dy);
    final steps = (dist / 10).floor();
    for (int i = 0; i < steps; i += 2) {
      final t0 = i / steps;
      final t1 = (i + 1) / steps;
      canvas.drawLine(
        Offset(start.dx + dx * t0, start.dy + dy * t0),
        Offset(start.dx + dx * t1, start.dy + dy * t1),
        paint,
      );
    }
  }

  void _drawPin(Canvas canvas, Offset pos, Color color) {
    canvas.drawCircle(pos, 14, Paint()
      ..color = color.withValues(alpha: 0.3)
      ..maskFilter = const MaskFilter.blur(BlurStyle.normal, 10));
    canvas.drawCircle(pos, 9, Paint()..color = color);
    canvas.drawCircle(pos, 9, Paint()
      ..color = Colors.white.withValues(alpha: 0.3)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1.5);
    canvas.drawCircle(pos, 3, Paint()..color = Colors.white);
  }

  @override
  bool shouldRepaint(_NightMapPainter _) => false;
}

// ─── Background bokeh for this screen ────────────────────────────────────────
class _NightBokeh extends StatelessWidget {
  const _NightBokeh();

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        gradient: RadialGradient(
          center: Alignment(-0.6, -0.7),
          radius: 0.6,
          colors: [Color(0x16C87010), Colors.transparent],
        ),
      ),
    );
  }
}
